MyNovel/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from MyNovel import settings
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app.urls','app'),namespace='novel'))
]

app/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from MyNovel import settings
from app import views

urlpatterns = [
    re_path(r'index/(?P<page_num>\d+)$',views.indexPage,name='index'),
    path('test/',views.testT),
    re_path('chapter/(?P<book_id>\d+)$',views.novleChapters,name='chapter'),
    re_path(r'content/(?P<book_id>\d+)/(?P<chapter_num>\d+)$',views.novelContent,name='content'),
    path('search/',views.searchNovel,name='search'),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

app/models.py
from django.db import models

# Create your models here.

class Novels(models.Model):
    book_name = models.CharField(max_length=50)
    author = models.CharField(max_length=20)
    resume = models.CharField(max_length=200)
    images = models.ImageField(upload_to='images')

class Chapters(models.Model):
    title = models.CharField(max_length=50)
    belong = models.CharField(max_length=10)
    chapter_url = models.CharField(max_length=100)
    chapter_num = models.CharField(max_length=5)

class TestModeln(models.Model):
    bookname = models.CharField(max_length=10)
    img = models.ImageField(upload_to='images')

app/views.py
import json
import os
from django.http import HttpResponse
from django.shortcuts import render
from .models import *
from django.core.paginator import Paginator

from django.urls import reverse

# Create your views here.

#首页
def indexPage(request,page_num):
    novel_list = Novels.objects.all().order_by('id')    #加order_by('id')防止发生无序排序
    paginator = Paginator(novel_list,10)    #分页
    page_num = int(page_num)
    if page_num > 8:
        page_num = 8
    try:
        data = paginator.page(int(page_num))
    except Exception as e:
        data = []
    num_list = [1,2,3,4,5,6,7,8]
    if page_num <= 4:
        pNum_list = num_list[page_num-1:page_num+3]
    else:
        pNum_list = num_list[4:]
    if page_num <= 1:
        last_page = 1
    else:
        last_page = page_num-1
    if page_num >= 8:
        next_page = 8
    else:
        next_page = page_num+1
    # for d in data:
    #     print(d.book_name)
    # print(len(data))
    return render(request,'index.html',{'pNum_list':pNum_list,'last_page':last_page,'next_page':next_page,
                                        'row1':data[:5],'row2':data[5:]})

#小说内容
def novelContent(request,book_id,chapter_num):
    novel = Novels.objects.filter(id=book_id)[0]
    chapter = Chapters.objects.filter(belong=book_id,chapter_num=chapter_num)[0]
    fb = open(chapter.chapter_url,'r')
    content = fb.read().split('\n')
    fb.close()
    chapter_num = int(chapter_num)
    chapter_list = Chapters.objects.filter(belong=book_id)
    chapter_total = len(chapter_list)
    if chapter_num <=1:
        last_chapter = 1
    else:
        last_chapter = chapter_num-1
    if chapter_num >= chapter_total:
        next_chapter = chapter_total
    else:
        next_chapter = chapter_num+1
    title = chapter.title
    return render(request,'content.html',{'novel':novel,'content':content,'last_chapter':last_chapter,'next_chapter':next_chapter,
                                          'title':title})

#小说章节
def novleChapters(request,book_id):
    novel = Novels.objects.filter(id=book_id)
    chapter_list = Chapters.objects.filter(belong=book_id)
    return render(request,'chapters.html',{'novel':novel[0],'chapter_list':chapter_list})

#搜索小说
def searchNovel(requests):
    if requests.method == 'POST':
        keyword = requests.POST.get('keyword')
        print(keyword)
        if keyword :
            novel = Novels.objects.filter(book_name__icontains=keyword) #包含查询
            if len(novel) > 0:
                return render(requests,'search.html',{'data':novel})
            else:
                return HttpResponse('对不起，没有查询到你要查找的小说')
        else:
            return HttpResponse('请输入关键词搜索')

DIR = "media/novels"

def get_file_list(file_path):
    dir_list = os.listdir(file_path)
    if not dir_list:
        print('没有此目录')
        return
    else:
        # 注意，这里使用lambda表达式，将文件按照最后修改时间顺序升序排列
        # os.path.getmtime() 函数是获取文件最后修改时间
        # os.path.getctime() 函数是获取文件最后创建时间
        dir_list = sorted(dir_list,  key=lambda x: os.path.getmtime(os.path.join(file_path, x)))
        # print(dir_list)
        return dir_list

def testT(request):
    # dir_list = get_file_list(DIR)
    # fb = open('%s/三国之凉人崛起/chapters/第一章 马家三郎.txt'%DIR,'r')
    # a = fb.read().split('\n')
    # fb.close()
    # print(a)

    # bid = 1
    # for name in dir_list:
    #     chapter_path = os.path.join(DIR,name,'chapters').replace('\\','/')
    #     chapter_list = get_file_list(chapter_path)
    #     chapter_num = 0
    #     for chapter in chapter_list:
    #         title = chapter.replace('.txt','')
    #         chapter_url = os.path.join(chapter_path,chapter).replace('\\','/')
    #         chapter_num += 1
    #         Chapters.objects.create(title=title,belong=bid,chapter_num=chapter_num,chapter_url=chapter_url)
    #     bid += 1
            # Chapters.objects.create()

    # for name in dir_list:
    #     json_path = os.path.join(DIR,name,'resume/%s.json'%name).replace('\\','/')
    #     fb = open(json_path,'r')
    #     novel_msg = json.load(fb)
    #     image = os.path.join('novels',name,'images/%s.jpg'%name).replace('\\','/')
    #     resume = novel_msg['resume']
    #     author = novel_msg['author']
    #     book_name = novel_msg['book_name']
    #     target = Novels.objects.filter(id=bid)
    #     bid += 1
    #     target.update(book_name=book_name,images=image,resume=resume,author=author)
    #     # Novels.objects.update(book_name=book_name,images=image,resume=resume,author=author)
    #     print(image)
    url = reverse('novel:index',kwargs={'page_num':1})  #关键字参数用kwargs 字典传入
    #url = reverse('novel:index', args=(1,))   #位置参数用args 元组传入
    return HttpResponse('%s'%url)

templates/chapters.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>小说详情页</title>
    <link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/static/css/detail.css">
</head>
<body>
    <!-- 头部分 -->
    <header>
        <div class="container">
            <div class="img">
                <a href="{% url 'novel:index' page_num=1 %}">
                    <img src="/static/images/logo.png" alt="" srcset="">
                </a>
            </div>
            <form action="{% url 'novel:search' %}" class="frm" method="post">
                {% csrf_token %}
                <input type="text" class="search-vl" placeholder="请输入小说名..." name="keyword">
                <button type="submit" class="search-btn">搜索</button>
            </form>
        </div>
    </header>
    <!-- 主体部分 -->
    <section>
        <div class="container">
            <div class="row">
                <div class="img">
                   <a href="{% url 'novel:content' book_id=novel.id chapter_num=1 %}">
                        <img src="{{ novel.images.url }}" alt="" srcset="">
                   </a>
                </div>
                <div class="detail">
                    <p><h3>{{ novel.book_name }}</h3></p>
                    <p>
                        <span>作者：{{ novel.author }}</span>
                    </p>
                    <p style="height: 60px; overflow: auto;">简介：{{ novel.resume }}</p>
                    <p>完结</p>
                    <p><a href="{% url 'novel:content' book_id=novel.id chapter_num=1 %}">立刻阅读</a></p>
                </div>
                <div class="row">
                    <h3 style="text-align: center;margin: 15px 0;">全部章节</h3>
                    <ul class="items">
                        {% for chapter in chapter_list %}
                            <li class="item">
                            <a href="{% url 'novel:content' book_id=novel.id chapter_num=chapter.chapter_num %}">{{ chapter.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

templates/content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>小说第一章</title>
    <link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/static/css/comtent.css">
</head>
<body>
    <!-- 头部分 -->
    <header>
        <div class="container">
            <div class="img">
                <a href="{% url 'novel:index' page_num=1 %}">
                    <img src="/static/images/logo.png" alt="" srcset="">
                </a>
            </div>
            <form action="{% url 'novel:search' %}" class="frm" method="post">
                {% csrf_token %}
                <input type="text" class="search-vl" placeholder="请输入小说名..." name="keyword">
                <button type="submit" class="search-btn">搜索</button>
            </form>
        </div>
    </header>
    <!-- 内容部分 -->
    <section>
        <div class="container">
            <div class="row">
                <h3 style="text-align: center;margin: 15px 0;">{{ title }}</h3>
                <p style="font-size: 12px;color: #666;text-align: center;margin: 15px 0;">
                    <span>作者：{{ novel.author }}</span>
                </p>
                <hr/>
                <!-- 小说内容 -->
                <!-- 用那个pre原格式不可行，不然你就直接扔在这，不然我也没办法 -->
                <div class="main">
                    {% for p in content %}
                        <p style="text-indent: 2em; margin-bottom: 30px;">
                            {{ p }}
                        </p>
                    {% endfor %}

                </div>
                <div class="page">
                    <ul>
                        <li><a href="{% url 'novel:content' book_id=novel.id chapter_num=last_chapter %}">上一章</a></li>
                        <li><a href="{% url 'novel:content' book_id=novel.id chapter_num=next_chapter %}">下一章</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>奇想小说</title>
    <link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/static/css/index.css">
</head>
<body>
    <!-- 头部分 -->
    <header>
        <div class="container">
            <div class="img">
                <a href="{% url 'novel:index' page_num=1 %}">
                    <img src="/static/images/logo.png" alt="" srcset="">
                </a>
            </div>
            <form action="{% url 'novel:search' %}" class="frm" method="post">
                {% csrf_token %}
                <input type="text" class="search-vl" placeholder="请输入小说名..." name="keyword">
                <button type="submit" class="search-btn" >搜索</button>
            </form>
        </div>
    </header>
    <!-- 主体部分 -->
    <section>
        <div class="container">
            <div class="row">
                {% for novel in row1 %}
                    <div>
                    <a href="{% url 'novel:chapter' book_id=novel.id %}">
                        <img src="{{ novel.images.url }}" alt="" srcset="">
                        <div class="info">
                            <h3>小说：{{ novel.book_name }}</h3>
                            <p>{{ novel.resume }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}

            </div>
            <div class="row">
                {% for novel in row2 %}
                    <div>
                    <a href="{% url 'novel:chapter' book_id=novel.id %}">
                        <img src="{{ novel.images.url }}" alt="" srcset="">
                        <div class="info">
                            <h3>小说：{{ novel.book_name }}</h3>
                            <p>{{ novel.resume }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}

            </div>
        </div>
        <div class="container">
            <div class="page">
                <ul>
                    <li><a href="{% url 'novel:index' page_num=last_page %}">上一页</a></li>
                    {% for n in pNum_list %}
                        <li><a href="{% url 'novel:index' page_num=n %}">{{ n }}</a></li>
                    {% endfor %}
                    <li><a href="{% url 'novel:index' page_num=next_page %}">下一页</a></li>
                </ul>
            </div>
        </div>
    </section>
</body>
</html>

templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>奇想小说</title>
    <link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/static/css/index.css">
</head>
<body>
    <!-- 头部分 -->
    <header>
        <div class="container">
            <div class="img">
                <a href="{% url 'novel:index' page_num=1 %}">
                    <img src="/static/images/logo.png" alt="" srcset="">
                </a>
            </div>
            <form action="{% url 'novel:search'  %}" class="frm" method="post">
                {% csrf_token %}
                <input type="text" class="search-vl" placeholder="请输入小说名..." name="keyword">
                <button type="submit" class="search-btn" >搜索</button>
            </form>
        </div>
    </header>
    <!-- 主体部分 -->
    <section>
        <div class="container">
            <div class="row">
                {% for novel in data %}
                    <div>
                    <a href="{% url 'novel:chapter' book_id=novel.id %}">
                        <img src="{{ novel.images.url }}" alt="" srcset="">
                        <div class="info">
                            <h3>小说：{{ novel.book_name }}</h3>
                            <p>{{ novel.resume }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
</body>
</html>